### ISSUE TITLE
Hide Console and Detecetions

### ISSUE THREAD

**Issue by jamiekarvans** [KDot227/Bat2Exe#1]
hi nice and simple code, but the console of batch file is visible, i think it would be alot better to hide the console and turn off debug mode, also it's detected by 16/70 on virustotal , i think it would be nice to add some junk code to the app to make it undetecteable
a very good idea is to just add dropper code to a legit app so wouldn't rise any suspecious

**Comment by KDot227** [comment]
> but the console of batch file is visible, i think it would be alot better to hide the console and turn off debug mode, also it's detected by 16/70 on virustotal , i think it would be nic

I made a fud dropper + in somalifuscator it has a method for exe2bat which turns an exe file into a bat file and it's fud. Sorry for the high detections on this.

**Comment by jamiekarvans** [comment]
> > but the console of batch file is visible, i think it would be alot better to hide the console and turn off debug mode, also it's detected by 16/70 on virustotal , i think it would be nic
> 
> I made a fud dropper + in somalifuscator it has a method for exe2bat which turns an exe file into a bat file and it's fud. Sorry for the high detections on this.

the fud dropper will still give back bat and ps1 format not exe which makes it suspecious and the somalifuscator unfortunately in all of the methods the console is still visible and it's not hidden

**Comment by KDot227** [comment]
> > > but the console of batch file is visible, i think it would be alot better to hide the console and turn off debug mode, also it's detected by 16/70 on virustotal , i think it would be nic
> > 
> > 
> > I made a fud dropper + in somalifuscator it has a method for exe2bat which turns an exe file into a bat file and it's fud. Sorry for the high detections on this.
> 
> the fud dropper will still give back bat and ps1 format not exe which makes it suspecious and the somalifuscator unfortunately in all of the methods the console is still visible and it's not hidden

Make it so your exe hides console

**Comment by EvilBytecode** [comment]
yh either you can use my code on my github ( https://github.com/EvilBytecode/HideConsoleWindows ) 
or just recompile and add your code, my has support in powershell,batch, and python :}. and c# since the powershell executes c# code lolz

**Comment by KDot227** [comment]
> yh either you can use my code on my github ( https://github.com/EvilBytecode/HideConsoleWindows ) 
> 
> or just recompile and add your code, my has support in powershell,batch, and python :}. and c# since the powershell executes c# code lolz

In this case it would be easier for me to add it straight to the js code for when it compiles. I'm also going to add support for command line args too.

**Comment by KDot227** [comment]
I also plan to make it follow through the current window so new ones aren't created.

**Comment by EvilBytecode** [comment]
nice 👍

**Comment by KDot227** [comment]
ALL DONE
