### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by grumach** [KDot227/Bat2Exe#2]
![image](https://github.com/KDot227/Bat2Exe/assets/110260624/92fddf66-39ad-4d96-9402-4e2952d858c7)

get this error when using the builder.bat. When I use the builder.py just no response in window program just closes

**Comment by KDot227** [comment]
> ![image](https://github.com/KDot227/Bat2Exe/assets/110260624/92fddf66-39ad-4d96-9402-4e2952d858c7)
> 
> 
> 
> get this error when using the builder.bat. When I use the builder.py just no response in window program just closes

Look for index.exe in the same folder as build.bat I think it worked.

**Comment by grumach** [comment]
I ran the index.exe with the obfuscated .bat and the non obfuscated .bat and both times it opened but didnt send anything to the webhook. It does try to run as admin and outputs a .bat then removes it but nothing else from what I can tell.

**Comment by KDot227** [comment]
> I ran the index.exe with the obfuscated .bat and the non obfuscated .bat and both times it opened but didnt send anything to the webhook. It does try to run as admin and outputs a .bat then removes it but nothing else from what I can tell.

Turn off both settings for bat2exe like delete file. That's the issue.

**Comment by grumach** [comment]
Works now thank you legend. Keep coding better content 🙏🙏
